# proto-file: config.proto
# proto-message: UprobestatsConfig

tasks {
  probe_configs {
    bpf_name: "prog_GenericInstrumentation_uprobe_call_detail"
    fully_qualified_class_name: "com.android.uprobestats.testapk.InstrumentationTestActivity"
    method_name: "testPrimitiveArgs"
    fully_qualified_parameters: ["int", "boolean", "long"]
  }
  bpf_maps: "map_GenericInstrumentation_call_detail_buf"
  target_process_name: "com.android.uprobestats.testapk"
  duration_seconds: 5
  statsd_logging_config {
    atom_id: 915
    primitive_argument_positions: [0, 1, 2]
  }
}
