# proto-file: config.proto
# proto-message: UprobestatsConfig

tasks {
  probe_configs {
    bpf_name: "prog_GenericInstrumentation_uprobe_call_timestamp"
    fully_qualified_class_name: "com.android.uprobestats.resolvetest.ResolveTestActivity"
    method_name: "customMethodToTrace"
  }
  bpf_maps: "map_GenericInstrumentation_call_timestamp_buf"
  target_process_name: "com.android.uprobestats.resolvetest"
  duration_seconds: 5
}
