# proto-file: config.proto
# proto-message: UprobestatsConfig

tasks {
    probe_configs {
        bpf_name: "prog_GenericInstrumentation_uprobe_call_timestamp_1"
        file_paths: ["/system/framework/oat/arm64/services.odex","/system/framework/oat/x86_64/services.odex"]
        method_signature: "void com.android.server.am.BatteryStatsService.noteScreenState(int)"
    }
    bpf_maps: "map_GenericInstrumentation_call_timestamp_buf"
    target_process_name: "system_server"
    duration_seconds: 60
    statsd_logging_config {
        atom_id: 915
        primitive_argument_positions: [0]
    }
}
