# proto-file: config.proto
# proto-message: UprobestatsConfig

tasks {
    probe_configs {
        bpf_name: "prog_GenericInstrumentation_uprobe_call_timestamp_1"
        fully_qualified_class_name: "com.android.server.am.BatteryStatsService"
        method_name: "setBatteryState"
        fully_qualified_parameters: ["int", "int", "int", "int", "int", "int", "int", "int", "long"]
    }
    bpf_maps: "map_GenericInstrumentation_call_timestamp_buf"
    target_process_name: "system_server"
    duration_seconds: 60
    statsd_logging_config {
        atom_id: 915
    }
}
